//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightPlanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Expressions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Expressions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlightPlanner.Expressions", typeof(Expressions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=type=\&quot;checkbox\&quot;)\\s*(?:id=\&quot;)(.*)(?:\&quot;\\s* name = \&quot;aircraftsContainer\&quot;\\s* value =\&quot;check\\d*\&quot;&gt;\\s*.*\\s*.*\\s*&lt;span&gt;)(.*)(?:&lt;\\/span&gt;\\s*.*\\s*.*\\s*.*\&quot; &gt;)(.*)(?:&lt;\\/ span &gt;\\s *.*\\s *.*\\s *.*\\s *.*\\s *.* id =)(\\d *)(?:\&quot;&gt;)(.*)(?:&lt;\\/a&gt;\\s*.*\\s*.*\\s*.*\&quot; &gt;)(.*)(?:&lt;\\/ a &gt;\\s *.*\\s *.\\s *.*\\s *.*&gt;)(.*)(?:\\syrs.*\\s *.*\\s.* \&quot;&gt;)(.*)(?:%.*\\s*.*\\s*.*\&quot; &gt;)(.*)(?:%.*\\s *.*\\s *.*\\s *.*\\s *&lt; span &gt;)(\\d *)(?:&lt;\\/ span &gt;\\/&lt; span &gt;)(\\d *)(?:&lt;\\/ span &gt;\\/&lt; span &gt;)(\\d *)(?:.*).
        /// </summary>
        internal static string GetAircraftFromFleet {
            get {
                return ResourceManager.GetString("GetAircraftFromFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=aircraftsType\?id=)(\d*).
        /// </summary>
        internal static string GetAircraftID {
            get {
                return ResourceManager.GetString("GetAircraftID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=&lt;td&gt;)(.*)(?:\/td&gt;\s*.*)(?:number&quot;&gt;)(.*)(?:&lt;\/td&gt;\s*.*number&quot;&gt;)(.*)(?:&lt;\/td&gt;\s*.*number&quot;&gt;)(.*)(?:&lt;\/td&gt;\s*.*\s*.*number&quot;&gt;)(\d*)(?:.*\s*.*\s*&lt;span&gt;)(\d*)(?:\D*)(\d*)(?:\D*)(\d*)(?:\D*)(\d*)(?:(?s).*?editor/)(\d*).
        /// </summary>
        internal static string GetConfigurationInformation {
            get {
                return ResourceManager.GetString("GetConfigurationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;={0} km&lt;\/th&gt;)(?:\s*.*\s*.*rating\/)(\d*)(?:.*\s*.*\s.*rating\/)(\d*)(?:.*\s*.*\s.*rating\/)(\d*).
        /// </summary>
        internal static string GetConfigurationRating {
            get {
                return ResourceManager.GetString("GetConfigurationRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=&lt;a href=\&quot;\\./fleets/)(.*)(?=\&quot;&gt;&lt;span&gt;).
        /// </summary>
        internal static string GetFleetIDs {
            get {
                return ResourceManager.GetString("GetFleetIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=&lt;a href=\&quot;\\./fleets/\\S*&lt;span&gt;)(.*)(?=&lt;/span&gt;).
        /// </summary>
        internal static string GetFleetNames {
            get {
                return ResourceManager.GetString("GetFleetNames", resourceCulture);
            }
        }
    }
}
