//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightPlanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebCookies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebCookies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlightPlanner.WebCookies", typeof(WebCookies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %7B%22p%22%3A%22as%22%2C%22r%22%3A%22https%3A%5C%2F%5C%2Fwww.airlinesim.aero%5C%2Fblog%5C%2Fcategory%5C%2Fdev-log%5C%2F%22%2C%22lh%22%3A%22www.airlinesim.aero%22%2C%22lu%22%3A%22%5C%2Fen%5C%2Ftechnology-demonstrator%22%2C%22lq%22%3A%22%22%7D.
        /// </summary>
        internal static string ASFC {
            get {
                return ResourceManager.GetString("ASFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 740.
        /// </summary>
        internal static string ENT {
            get {
                return ResourceManager.GetString("ENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to node0157k6ratz0ycyloa56mw7pwr110412.node0.
        /// </summary>
        internal static string JSESSIONID {
            get {
                return ResourceManager.GetString("JSESSIONID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https%3A%2F%2Fwww.airlinesim.aero%2Fblog%2F2023%2F07%2F27%2Fairlinesim-events-2023-announcement%2F.
        /// </summary>
        internal static string LP {
            get {
                return ResourceManager.GetString("LP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TajrCpZmPLxyVhTjkkpdo7dSOrLobQ9Q_qPuwahYICv4etWCl5WJZL0E6hby5mInN.
        /// </summary>
        internal static string SID {
            get {
                return ResourceManager.GetString("SID", resourceCulture);
            }
        }
    }
}
