
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace FlightPlanner.Displays {
    using System;
    using Terminal.Gui;
    
    
    public partial class Fleets : Terminal.Gui.Window {
        
        private Terminal.Gui.FrameView fleetListFrame;
        
        private Terminal.Gui.ListView fleetList;
        
        private Terminal.Gui.FrameView informationFrame;
        
        private Terminal.Gui.FrameView planeListFrame;

        private Terminal.Gui.ListView planeList;

        private Terminal.Gui.ListWrapper fleetListInteractive;

        private Terminal.Gui.ListWrapper planeListInteractive;
        
        private void InitializeComponent() {
            fleetListInteractive = new ListWrapper(new string[] { });
            planeListInteractive = new ListWrapper(new string[] { });

            this.planeListFrame = new Terminal.Gui.FrameView();
            this.planeList = new Terminal.Gui.ListView();
            this.informationFrame = new Terminal.Gui.FrameView();
            this.fleetList = new Terminal.Gui.ListView();
            this.fleetListFrame = new Terminal.Gui.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.fleetListFrame.Width = Dim.Percent(20f);
            this.fleetListFrame.Height = Dim.Percent(70f);
            this.fleetListFrame.X = 0;
            this.fleetListFrame.Y = 0;
            this.fleetListFrame.Visible = true;
            this.fleetListFrame.Data = "fleetListFrame";
            this.fleetListFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.fleetListFrame.Border.Effect3D = false;
            this.fleetListFrame.Border.Effect3DBrush = null;
            this.fleetListFrame.Border.DrawMarginFrame = true;
            this.fleetListFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.fleetListFrame.Title = "FLEETS";
            this.Add(this.fleetListFrame);
            this.fleetList.Width = Dim.Percent(100f);
            this.fleetList.Height = Dim.Percent(100f);
            this.fleetList.X = 0;
            this.fleetList.Y = 0;
            this.fleetList.Visible = true;
            this.fleetList.Data = "fleetList";
            this.fleetList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.fleetList.Source = fleetListInteractive;
            this.fleetList.AllowsMarking = false;
            this.fleetList.AllowsMultipleSelection = true;
            this.fleetListFrame.Add(this.fleetList);
            this.informationFrame.Width = Dim.Percent(80f);
            this.informationFrame.Height = Dim.Percent(70f);
            this.informationFrame.X = Pos.Right(fleetListFrame);
            this.informationFrame.Y = Pos.Percent(0f);
            this.informationFrame.Visible = true;
            this.informationFrame.Data = "informationFrame";
            this.informationFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.informationFrame.Border.Effect3D = false;
            this.informationFrame.Border.Effect3DBrush = null;
            this.informationFrame.Border.DrawMarginFrame = true;
            this.informationFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.informationFrame.Title = "";
            this.Add(this.informationFrame);
            this.planeListFrame.Width = Dim.Fill(0);
            this.planeListFrame.Height = Dim.Percent(30f);
            this.planeListFrame.X = 0;
            this.planeListFrame.Y = Pos.Bottom(fleetListFrame);
            this.planeListFrame.Visible = true;
            this.planeListFrame.Data = "planeListFrame";
            this.planeListFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.planeListFrame.Border.Effect3D = false;
            this.planeListFrame.Border.Effect3DBrush = null;
            this.planeListFrame.Border.DrawMarginFrame = true;
            this.planeListFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.planeListFrame.Title = "PLANES";
            this.Add(this.planeListFrame);
            this.planeList.Width = Dim.Percent(100f);
            this.planeList.Height = Dim.Percent(100f);
            this.planeList.X = 0;
            this.planeList.Y = 0;
            this.planeList.Visible = true;
            this.planeList.Data = "planeList";
            this.planeList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.planeList.Source = planeListInteractive;
            this.planeList.AllowsMarking = false;
            this.planeList.AllowsMultipleSelection = true;
            this.planeListFrame.Add(this.planeList);
        }
    }
}
