
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace FlightPlanner.Displays {
    using System;
    using Terminal.Gui;
    
    
    public partial class Login : Terminal.Gui.Window {
        
        private Terminal.Gui.FrameView loginFrame;
        
        private Terminal.Gui.Label serverLabel;
        
        private Terminal.Gui.TextField serverInput;
        
        private Terminal.Gui.Button enterButton;
        
        private void InitializeComponent() {
            this.enterButton = new Terminal.Gui.Button();
            this.serverInput = new Terminal.Gui.TextField();
            this.serverLabel = new Terminal.Gui.Label();
            this.loginFrame = new Terminal.Gui.FrameView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.loginFrame.Width = 48;
            this.loginFrame.Height = 8;
            this.loginFrame.X = Pos.Center();
            this.loginFrame.Y = Pos.Center();
            this.loginFrame.Visible = true;
            this.loginFrame.Data = "loginFrame";
            this.loginFrame.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.loginFrame.Border.Effect3D = false;
            this.loginFrame.Border.Effect3DBrush = null;
            this.loginFrame.Border.DrawMarginFrame = true;
            this.loginFrame.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.loginFrame.Title = "Heya";
            this.Add(this.loginFrame);
            this.serverLabel.Width = 6;
            this.serverLabel.Height = 1;
            this.serverLabel.X = Pos.Left(serverInput) - 7;
            this.serverLabel.Y = Pos.Bottom(serverInput) - 1;
            this.serverLabel.Visible = true;
            this.serverLabel.Data = "serverLabel";
            this.serverLabel.Text = "Server";
            this.serverLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.loginFrame.Add(this.serverLabel);
            this.serverInput.Width = 32;
            this.serverInput.Height = 1;
            this.serverInput.X = 11;
            this.serverInput.Y = 2;
            this.serverInput.Visible = true;
            this.serverInput.Secret = false;
            this.serverInput.Data = "serverInput";
            this.serverInput.Text = "";
            this.serverInput.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.loginFrame.Add(this.serverInput);
            this.enterButton.Width = 6;
            this.enterButton.Height = 1;
            this.enterButton.X = Pos.Right(serverInput) - 6;
            this.enterButton.Y = Pos.Bottom(serverInput) + 1;
            this.enterButton.Visible = true;
            this.enterButton.Data = "enterButton";
            this.enterButton.Text = "OK";
            this.enterButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.enterButton.IsDefault = false;
            this.loginFrame.Add(this.enterButton);
        }
    }
}
