
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace FlightPlanner.Displays {
    using System;
    using Terminal.Gui;
    
    
    public partial class Operator : Terminal.Gui.Window {
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem aIRCRAFTMenu;
        
        private Terminal.Gui.MenuItem fLEETSMenuItem;
        
        private Terminal.Gui.MenuItem mARKETPLACEMenuItem;
        
        private Terminal.Gui.MenuItem mANUFACTURERSMenuItem;
        
        private Terminal.Gui.MenuBarItem rOUTINGMenu;
        
        private Terminal.Gui.MenuItem editMeMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.aIRCRAFTMenu = new Terminal.Gui.MenuBarItem();
            this.aIRCRAFTMenu.Title = "AIRCRAFT";
            this.fLEETSMenuItem = new Terminal.Gui.MenuItem();
            this.fLEETSMenuItem.Title = "FLEETS";
            this.fLEETSMenuItem.Data = "fLEETSMenuItem";
            this.mARKETPLACEMenuItem = new Terminal.Gui.MenuItem();
            this.mARKETPLACEMenuItem.Title = "MARKETPLACE";
            this.mARKETPLACEMenuItem.Data = "mARKETPLACEMenuItem";
            this.mANUFACTURERSMenuItem = new Terminal.Gui.MenuItem();
            this.mANUFACTURERSMenuItem.Title = "MANUFACTURERS";
            this.mANUFACTURERSMenuItem.Data = "mANUFACTURERSMenuItem";
            this.aIRCRAFTMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.fLEETSMenuItem,
                    this.mARKETPLACEMenuItem,
                    this.mANUFACTURERSMenuItem};
            this.rOUTINGMenu = new Terminal.Gui.MenuBarItem();
            this.rOUTINGMenu.Title = "ROUTING";
            this.editMeMenuItem = new Terminal.Gui.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.rOUTINGMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.aIRCRAFTMenu,
                    this.rOUTINGMenu};
            this.Add(this.menuBar);
        }
    }
}
