
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace FlightPlanner.Displays {
    using Terminal.Gui;
    
    
    public partial class Operator {
        
        public Operator() {
            InitializeComponent();
        }
    }
}
